DROP TABLE IF EXISTS user CASCADE;
DROP TABLE IF EXISTS user_friends CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS ratings CASCADE;
DROP TABLE IF EXISTS film CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS genres_film CASCADE;

create table if not exists user(
id int generated by default as identity primary key,
email varchar NOT NULL,
login varchar(255) NOT NULL,
name varchar(255),
birthday date NOT NULL
);

create table if not exists user_friends(
PRIMARY KEY(user_id, friend_id),
user_id int,
friend_id int,
FOREIGN KEY(user_id) REFERENCES user(id),
FOREIGN KEY(friend_id) REFERENCES user(id)
);

create table if not exists ratings(
rating_id int primary key,
name varchar(255)
);

create table if not exists film(
id int generated by default as identity primary key,
name varchar(255) NOT NULL,
description varchar(200) NOT NULL,
releaseDate date NOT NULL,
duration int,
rating_id int
);

create table if not exists likes(
PRIMARY KEY(user_id, film_id),
film_id int,
user_id int,
FOREIGN KEY(film_id) REFERENCES film(id),
FOREIGN KEY(user_id) REFERENCES user(id)
);

create table if not exists genre(
genre_id int primary key,
name varchar(255)
);

create table if not exists genres_film(
film_id int,
genre_id int,
FOREIGN KEY(film_id) REFERENCES film(id),
FOREIGN KEY(genre_id) REFERENCES genre(genre_id)
);